{
    'name': 'Inmoser Service Order',
    'version': '17.0.1.0.0',
    'summary': 'Service Order Management for Inmoser',
    'description': 'Complete module for managing service orders, equipment, and technicians',
    'category': 'Services',
    'author': 'Your Name',
    'depends': ['base', 'mail', 'account', 'hr', 'stock'],
    'external_dependencies': {
        'python': ['qrcode'],
    },
    'data': [
        'security/inmoser_service_order_groups.xml',
        'security/inmoser_service_order_security.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/inmoser_service_type_data.xml',
        'data/inmoser_service_order_mail_template.xml',
        'views/hr_employee_views.xml',
        'views/inmoser_service_equipment_views.xml',
        'views/inmoser_service_type_views.xml',
        'views/inmoser_service_order_views.xml',
        'views/inmoser_service_order_refaction_line_views.xml',
        'views/inmoser_service_specialty_views.xml',
        'views/account_move_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
